---
- name: Converge
  hosts: all
  roles:
    - role: ome.hosts_populate
      hosts_populate_openstack_groups: [all]
      # Can't replace /etc/hosts on Docker
      hosts_populate_etc_hosts: /etc/hosts-molecule
